### ISSUE TITLE
`autoencoder_scale` was something like 6.85

### ISSUE THREAD

**Issue by mkshing** [JD-P/cloob-latent-diffusion#7]
Hi, I am about to train my own cloob latent diffusion and would like to confirm this is right. 
`autoencoder_scale` in your example was about 100 but I got something like 6.85. 
It depends on the training dataset but I saw a different line in your previous log to compute the final scale. 
So, I just would like to double check if the master's code is doing right, or not. 
Thank you!

[in the previous commit](https://github.com/JD-P/cloob-latent-diffusion/commit/317437838623577288e8b341e4a36233247ecda9)
```
autoencoder_scale = torch.tensor(var_accum ** 0.5)
```
in the master branch 
```
autoencoder_scale = torch.tensor((var_accum / 32) ** 0.5)
```

**Comment by JD-P** [comment]
Yeah that's probably right, the scale of 109 was from an early version of the script that was calculating it wrong. I've since changed it to the autoencoder scale for the LAION 5b encoder as the default example.

**Comment by mkshing** [comment]
@JD-P Great! In fact, I got good results with the scale 👍
